version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres

  gunicorn:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    networks:
      - postgres
      - gunicorn
    command: poetry run gunicorn --timeout 10000 --bind 0.0.0.0:5000 wsgi:app
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: proxy
    ports:
      - 127.0.0.1:1234:80
      - 127.0.0.1:1237:443
    depends_on:
      - gunicorn
    networks:
      - gunicorn

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/root/.pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - 127.0.0.1:1235:80
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
  gunicorn:
    driver: bridge

volumes:
  postgres:
  pgadmin: