version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres

  flask:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - 127.0.0.1:1234:1234
    networks:
      - postgres
    command:
      poetry run main
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - 127.0.0.1:1236:80
      - 127.0.0.1:1237:443
    depends_on:
      - flask

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/root/.pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "1235:80"
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: